name: Deploy

on:
  push:
    branches:
      - master

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Build project
        env:
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: yarn build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v7
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: production-files
          path: ./dist

      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          neocities_supporter: false # set this to true if you have a supporter account and want to bypass unsuported files filter.
          preview_before_deploy: true # print a deployment plan prior to waiting for files to upload.
          dist_dir: dist
